project_id = "reconciliador-visteon"

[functions.myke-chat]
verify_jwt = false
entrypoint = "./functions/myke-chat/index.ts"

[functions.bot-notifications]
verify_jwt = false
entrypoint = "./functions/bot-notifications/index.ts"
