import {useEffect,useRef,useState} from "react";
export default function BotControlModal({open,onClose}){
 const [password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[status,setStatus]=useState(null);const requestRef=useRef(false);
 const endpoint=String(import.meta.env.VITE_BOT_CONTROL_URL||"").replace(/\/$/,"");
 const call=async(path)=>{const response=await fetch(`${endpoint}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data;};
 const refreshStatus=async()=>{if(!endpoint||!password)return;try{setStatus(await call("/bot/status"));}catch{/* no convertir un fallo de estado en éxito */}};
 useEffect(()=>{if(!open||!endpoint||!password)return;refreshStatus();const id=setInterval(refreshStatus,3000);return()=>clearInterval(id);},[open,endpoint,password]);
 const start=async()=>{if(requestRef.current)return;if(!endpoint){setMessage("Falta conectar el controlador seguro del bot. GitHub Pages no ejecuta Python por sí solo.");return;}if(!password){setMessage("Escribe la contraseña de autorización.");return;}requestRef.current=true;setBusy(true);setMessage("Enviando solicitud…");try{const data=await call("/bot/start");setMessage(data.state==="already_running"?"El proceso ya estaba ejecutándose.":"Solicitud aceptada. Esto todavía NO significa que el snapshot se haya publicado.");setStatus(data);await refreshStatus();}catch(error){setMessage(`No se aceptó la solicitud: ${error.message}`);}finally{requestRef.current=false;setBusy(false);}};
 if(!open)return null;
 const snap=status?.lastSnapshot;
 return <div className="vi-drawer-backdrop fixed inset-0 z-[145] bg-black/55" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><aside className="vi-drawer-panel"><div className="sticky top-0 z-10 px-5 py-5"><div className="flex justify-between gap-4"><div><p className="vi-eyebrow">CONTROL 4WALL</p><h2 className="mt-1 text-xl font-black">Ejecutar bot</h2><p className="mt-1 text-[11px]">Arranque y publicación son estados distintos.</p></div><button className="vi-button" onClick={onClose}>CERRAR</button></div></div><div className="vi-bot-form"><div className="vi-bot-status">El controlador debe estar protegido por autenticación y HTTPS/red autorizada. La contraseña no se guarda en el frontend.</div><label>CONTRASEÑA DE AUTORIZACIÓN<input className="vi-input" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")start();}}/></label><button className="vi-button vi-button-primary" disabled={busy} onClick={start}>{busy?"SOLICITANDO…":"▶ SOLICITAR ARRANQUE"}</button>{message&&<p className="vi-bot-status" role="status">{message}</p>}{status&&<div className="vi-bot-state"><strong>Proceso: {status.processState||status.state||"desconocido"}</strong><span>{status.pid?`PID ${status.pid}`:"Sin PID activo"}</span>{snap?<><strong>Último snapshot: {snap.result||"desconocido"}</strong><span>ID {snap.snapshotId||"—"} · {snap.rowCount??"—"} filas</span><span>Extraído {snap.extractedAt?new Date(snap.extractedAt).toLocaleString("es-MX"):"—"} · Publicado {snap.publishedAt?new Date(snap.publishedAt).toLocaleString("es-MX"):"—"}</span></>:<span>Aún no hay resultado de publicación reportado por el extractor.</span>}</div>}</div></aside></div>;
}
