import {useEffect,useMemo,useState} from "react";
import {buildSnapshot,snapshotsComparable} from "../../domain/buildDiscrepancyFindings.js";
export const CUT_STORAGE_KEY="visteon.inventory.meetingCuts.v3";
const LEGACY_KEYS=["visteon.inventory.meetingCuts.v2","visteon.inventory.meetingCuts.v1"],MAX_CUTS=24;
export const RULES_VERSION="2026-09-28-discrepancy-v2";
const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)||0);
function loadCuts(){try{for(const key of [CUT_STORAGE_KEY,"visteon.inventory.meetingCuts.v2"]){const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))return parsed;}}return [];}catch{return [];}}
function refs(s={}){return ["areas","qad","ispbb","bom","cost"].map(type=>({type,fingerprint:s[type]?.fingerprint||"",fileName:s[type]?.fileName||""}));}
export default function CutHistoryPanel({canSave=false,summary,scanCount=0,lastUpdated,rows=[],sources={},snapshotMeta,campaignId,onCampaignIdChange,onLatestCut}){
 const [cuts,setCuts]=useState(loadCuts),[storageError,setStorageError]=useState("");const last=cuts[0]||null;
 useEffect(()=>{onLatestCut?.(last);},[last,onLatestCut]);
 const current=useMemo(()=>buildSnapshot({campaignId,rows,references:refs(sources),rulesVersion:RULES_VERSION,snapshotMeta,valid:canSave}),[campaignId,rows,sources,snapshotMeta,canSave]);
 const comparison=useMemo(()=>snapshotsComparable(last,current),[last,current]);
 const delta=useMemo(()=>!comparison.ok||!last||!summary?null:{netUsd:Number(summary.netUsd||0)-Number(last.summary?.netUsd||0),scans:Number(scanCount||0)-Number(last.scanCount||0)},[comparison,last,summary,scanCount]);
 const save=()=>{if(!canSave||!summary||!campaignId.trim()){setStorageError(!campaignId.trim()?"Escribe un ID de campaña antes de guardar.":"No se puede guardar mientras las fuentes estén cargando, incompletas o la actualización haya fallado.");return;}const cut={...current,summary:{netUsd:Number(summary.netUsd||0),grossLossUsd:Number(summary.grossLossUsd||0),grossGainUsd:Number(summary.grossGainUsd||0),swingUsd:Number(summary.swingUsd||0),swingPieces:Number(summary.swingPieces||0),qadOnlyCount:Number(summary.qadOnlyCount||0),unvaluedPartCount:Number(summary.unvaluedPartCount||0)},scanCount:Number(scanCount||0),fetchedAt:lastUpdated?new Date(lastUpdated).toISOString():null};const next=[cut,...cuts].slice(0,MAX_CUTS);try{localStorage.setItem(CUT_STORAGE_KEY,JSON.stringify(next));setCuts(next);setStorageError("");}catch(e){setStorageError("No se pudo guardar el corte en este navegador. No uses este historial como evidencia.");console.warn(e);}};
 const clear=()=>{try{localStorage.removeItem(CUT_STORAGE_KEY);LEGACY_KEYS.forEach(k=>localStorage.removeItem(k));setCuts([]);setStorageError("");}catch{setStorageError("No se pudo borrar el historial local.");}};
 return <section className="vi-panel vi-cut-history"><div className="vi-cut-history-head"><div><p className="vi-eyebrow">JUNTAS DE INVENTARIO</p><h2>Historial de cortes</h2><p>Las comparaciones requieren campaña explícita, mismas huellas, misma versión de reglas y snapshots completos.</p></div><div className="vi-cut-history-actions"><label className="vi-campaign-label">CAMPAÑA<input className="vi-input" value={campaignId} onChange={e=>onCampaignIdChange?.(e.target.value)} placeholder="Ej. INV-2026-09"/></label>{cuts.length>0&&<button className="vi-button" onClick={clear}>BORRAR HISTORIAL</button>}<button className="vi-button vi-button-primary" disabled={!canSave||!campaignId.trim()} onClick={save}>GUARDAR CORTE</button></div></div>
 {storageError&&<p className="vi-cut-error">{storageError}</p>}{last&&!comparison.ok&&<p className="vi-cut-warning">NO COMPARABLE: {comparison.reason}</p>}{delta&&<div className="vi-cut-delta"><span>DESDE EL ÚLTIMO CORTE COMPARABLE</span><strong>NET {money(delta.netUsd)}</strong><strong>{delta.scans>=0?"+":""}{delta.scans.toLocaleString("es-MX")} REGISTROS</strong></div>}
 {cuts.length===0?<p className="vi-cut-empty">Todavía no hay cortes guardados.</p>:<div className="vi-cut-list">{cuts.slice(0,6).map((cut,i)=><div className="vi-cut-row" key={cut.id}><div><strong>{new Date(cut.savedAt).toLocaleString("es-MX")}</strong><span>{cut.campaignId||"SIN CAMPAÑA"} · {cut.scanCount||0} registros · {cut.parts?.length||0} PN conservados</span></div><span>{money(cut.summary?.netUsd)}</span>{i===0&&<em>ÚLTIMO</em>}</div>)}</div>}
 <p className="vi-cut-local-note">Historial local: no se sincroniza entre equipos. Se conserva el detalle de todos los PN del corte, no solo el Top 10.</p></section>;
}
