import {useEffect,useMemo,useState} from "react";
import {groupFindingsByPart} from "../../domain/buildDiscrepancyFindings.js";
const money=v=>v===null?"SIN VALORAR":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)||0);
const FILTERS=[["ALL","TODAS"],["CANTIDAD","CANTIDAD"],["UBICACION","POSIBLE UBICACIÓN"],["CALIDAD","CALIDAD DE DATOS"],["SIN_VALORAR","SIN VALORAR"]];
function FindingDetail({finding,onClose}){if(!finding)return null;return <div className="vi-drawer-backdrop fixed inset-0 z-[135] bg-black/55" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><aside className="vi-drawer-panel"><div className="sticky top-0 z-10 px-5 py-5"><div className="flex justify-between gap-4"><div><p className="vi-eyebrow">DISCREPANCIA / {finding.ruleCode}</p><h2 className="mt-1 text-xl font-black">{finding.partNumber}</h2></div><button className="vi-button" onClick={onClose}>CERRAR</button></div></div><div className="vi-finding-detail"><section><h3>Qué encontramos</h3><p>{finding.whatFound}</p></section><section><h3>Qué podría explicarlo</h3><p>{finding.possibleExplanation}</p></section><section><h3>Qué revisar</h3><p>{finding.nextAction}</p></section><section><h3>Evidencia observada</h3>{finding.evidence.length?finding.evidence.map((e,i)=><p key={i}><strong>{e.source}:</strong> {e.detail}</p>):<p>No hay evidencia adicional disponible.</p>}</section><section><h3>Estados</h3><p>Valoración: <strong>{finding.valuationState.replaceAll("_"," ")}</strong> · Conteo: <strong>{finding.countState.replaceAll("_"," ")}</strong></p>{finding.firstDetected&&<p>Primera detección local: {new Date(finding.firstDetected).toLocaleString("es-MX")} · Última: {new Date(finding.lastDetected).toLocaleString("es-MX")}</p>}</section></div></aside></div>;}
export default function DiscrepancyFindingsPanel({findings=[],evaluationValid=false,evaluationReason="",focusFindingId,onFocusHandled}){
 const [filter,setFilter]=useState("ALL"),[detail,setDetail]=useState(null);
 useEffect(()=>{if(!focusFindingId)return;const f=findings.find(x=>x.id===focusFindingId);if(f)setDetail(f);onFocusHandled?.();},[focusFindingId,findings,onFocusHandled]);
 const filtered=useMemo(()=>filter==="ALL"?findings:findings.filter(f=>f.category===filter),[findings,filter]);
 const rows=useMemo(()=>groupFindingsByPart(filtered),[filtered]),unvalued=useMemo(()=>groupFindingsByPart(findings.filter(f=>f.category==="SIN_VALORAR")),[findings]);
 const counts=useMemo(()=>Object.fromEntries(FILTERS.map(([id])=>[id,groupFindingsByPart(id==="ALL"?findings:findings.filter(f=>f.category===id)).length])),[findings]);
 return <section className="vi-panel vi-findings"><div className="vi-findings-head"><div><p className="vi-eyebrow">JUNTAS CADA ~2 HORAS</p><h2>Discrepancias por investigar</h2><p>Un PN aparece una sola vez en la tabla aunque tenga varias etiquetas. Su NET se muestra una sola vez.</p></div><span className={evaluationValid?"vi-eval-ok":"vi-eval-wait"}>{evaluationValid?"EVALUACIÓN DISPONIBLE":"NO EVALUABLE"}</span></div><div className="vi-findings-filters">{FILTERS.map(([id,label])=><button key={id} className={filter===id?"is-active":""} onClick={()=>setFilter(id)}>{label}<b>{counts[id]}</b></button>)}</div>
 {!evaluationValid?<div className="vi-findings-empty"><strong>No se pudo evaluar el corte.</strong><span>{evaluationReason||"Faltan fuentes válidas o la actualización no terminó correctamente."}</span></div>:rows.length===0?<div className="vi-findings-empty"><strong>Sin hallazgos para este filtro.</strong><span>Las fuentes sí pudieron evaluarse.</span></div>:<div className="vi-findings-table-wrap"><table className="vi-findings-table"><thead><tr><th>PN</th><th>Etiquetas</th><th>NET</th><th>Localidades</th><th>Evidencia</th><th>Siguiente acción</th></tr></thead><tbody>{rows.map(row=><tr key={row.partNumber}><td><button onClick={()=>setDetail(row.findings[0])}>{row.partNumber}</button></td><td>{row.tags.map(t=><span className="vi-finding-tag" key={t}>{t}</span>)}</td><td className={row.netUsd===null?"vi-unvalued":row.netUsd<0?"vi-money-loss":"vi-money-gain"}>{money(row.netUsd)}</td><td>{row.locations.join(", ")||"—"}</td><td><button className="vi-link-button" onClick={()=>setDetail(row.findings[0])}>{row.findings.length} motivo{row.findings.length===1?"":"s"}</button></td><td>{row.findings[0]?.nextAction}</td></tr>)}</tbody></table></div>}
 {evaluationValid&&unvalued.length>0&&filter!=="SIN_VALORAR"&&<div className="vi-unvalued-list"><strong>Casos sin valorar: {unvalued.length} PN</strong><span>Lista independiente del impacto USD. No se suman como $0.</span></div>}<FindingDetail finding={detail} onClose={()=>setDetail(null)}/></section>;
}
