export const FINANCE_QUESTIONS=[
{id:"close",q:"¿Cómo sabemos que un conteo ya terminó?",why:"Sin una señal oficial, una pieza sin escaneo puede seguir pendiente.",example:"QAD espera 100 piezas y todavía no aparece físico.",need:"Campo, reporte o responsable que confirme pendiente, en proceso y cerrado."},
{id:"scope",q:"¿Qué localidades y sitios de QAD entran al resultado financiero?",why:"Docks, holds, almacenes externos u otros sitios pueden cambiar el total.",example:"Confirmar si una localidad externa cuenta igual que ZWHSE o ZWIP.",need:"Lista oficial de localidades y sitios incluidos o excluidos."},
{id:"freeze",q:"¿Cómo se usa el congelado de QAD y qué pasa con movimientos posteriores?",why:"Fuentes de horas distintas pueden crear diferencias que no son faltantes reales.",example:"Un movimiento posterior al congelado puede explicar una diferencia.",need:"Hora oficial del congelado y regla para movimientos posteriores."},
{id:"cost",q:"¿Qué costo y moneda debemos usar?",why:"Sin costo confiable sabemos que hay diferencia, pero no sus dólares.",example:"Un costo vacío o un símbolo $ solo no se toma como cero.",need:"Fuente oficial, moneda y tratamiento del costo cero."},
{id:"swing",q:"¿Cómo quiere Finanzas interpretar SWING?",why:"Ayuda a encontrar material en localidades distintas, pero falta confirmar su alcance.",example:"Hoy se suman diferencias absolutas por localidad y no se divide entre dos.",need:"Ejemplo aprobado y localidades que participan."},
{id:"bom",q:"¿Qué cobertura y reglas BOM aplican?",why:"Una coincidencia BOM es una pista; por sí sola no demuestra físico.",example:"Padre, componente, nivel, Usage y sitio deben corresponder al caso real.",need:"Export completo y un caso real validado."},
{id:"records",q:"¿Cómo identificamos un registro y un reconteo?",why:"Repetir Ticket/FIFO no basta para afirmar duplicación.",example:"Un segundo conteo puede ser corrección o reconteo válido.",need:"Clave única oficial y regla de reconteo/corrección."},
{id:"thresholds",q:"¿Qué cambios deben investigarse y quién los revisa?",why:"Los umbrales priorizan la junta; no cambian el cálculo financiero.",example:"Resaltar cambios grandes no significa confirmar un error.",need:"Umbrales operativos y rol responsable."}
];export default function PendingDecisions(){return null;}