const DECISIONS=[
 {q:"¿Cuándo se considera cerrado el conteo de un PN/área?",rule:"Sin fuente válida de cierre, el estado permanece DESCONOCIDO.",effect:"QAD positivo sin físico se muestra como 'Sin físico registrado', no como pérdida confirmada.",ask:"Fuente/campo oficial de pendiente, en proceso y cerrado."},
 {q:"¿Qué localidades y Sites entran al alcance financiero?",rule:"Se conserva la localidad exacta; no se inventan agrupaciones.",effect:"Externos, docks, holds y otros Sites pueden cambiar el alcance.",ask:"Lista oficial de inclusión/exclusión y Site aplicable."},
 {q:"¿Cómo se trata el congelado QAD y los movimientos posteriores?",rule:"El dashboard compara el corte cargado contra el físico disponible.",effect:"Archivos de horas/días distintos pueden crear discrepancias de prueba.",ask:"Momento oficial del congelado y tratamiento de movimientos posteriores."},
 {q:"¿Cost Total es el costo oficial y cuál es la moneda?",rule:"Costo ausente, '$' solo, inválido o contradictorio queda SIN VALORAR.",effect:"No se estiman dólares ni se presenta $0 como valor real.",ask:"Fuente, moneda y tratamiento de costo cero."},
 {q:"¿Cuál es la interpretación oficial de SWING?",rule:"Hoy suma |Físico(localidad)-QAD(localidad)| sin dividir entre 2.",effect:"El alcance de localidades cambia el indicador.",ask:"Ejemplo aprobado por Finanzas."},
 {q:"¿Qué cobertura y reglas BOM aplican?",rule:"Una coincidencia BOM sirve para investigar; no crea un ajuste nuevo.",effect:"Nivel, Site, Usage y evidencia del padre deben validarse.",ask:"Export completo y caso real padre→componente."},
 {q:"¿Cuál es la identidad oficial de un registro y cómo se manejan reconteos?",rule:"No se infiere duplicación por repetir Ticket/FIFO.",effect:"Sin identidad oficial no se puede clasificar repetición como duplicado.",ask:"Clave única oficial y regla de reconteo/corrección."},
 {q:"¿Qué umbrales y responsables aplican a la investigación?",rule:"Los umbrales de cambio son criterios configurables de revisión, no reglas financieras.",effect:"Determinan qué cambios se resaltan, no el NET.",ask:"Umbrales operativos y rol responsable de investigar."},
];
export default function PendingDecisions(){return <details className="vi-pending-decisions"><summary className="vi-pending-summary"><span>DECISIONES PENDIENTES CON FINANZAS</span><b>{DECISIONS.length} PENDIENTES</b></summary><div className="vi-pending-grid">{DECISIONS.map((item,index)=><details className="vi-decision-card" key={item.q} open={index===0}><summary>{item.q}<span>PENDIENTE DE CONFIRMAR</span></summary><div className="vi-decision-body"><p><strong>Regla actual:</strong> {item.rule}</p><p><strong>Efecto:</strong> {item.effect}</p><p><strong>Fuente / ejemplo solicitado:</strong> {item.ask}</p></div></details>)}</div></details>;}
