import assert from "node:assert/strict";
import * as XLSX from "xlsx";
import { parseDelimitedFile } from "../src/parsers/parseDelimitedFile.js";
import { rawScanObject } from "../src/domain/scanView.js";
import { combineLibraries } from "../src/services/bomCloud.js";
import { mergeBomLibrary } from "../src/domain/bomLibrary.js";
const fields = [["Item Number"], ["Cost Total"], ["Status"]];
const book = XLSX.utils.book_new();
const sheet = XLSX.utils.aoa_to_sheet([["Título"], [], ["Item Number", "Cost Total", "Status"], [123, 1.23456, "Active"]]);
sheet.A4.z = "000000"; sheet.B4.z = "0.00";
XLSX.utils.book_append_sheet(book, sheet, "Costos");
const file = () => ({name:"cost.xlsx",arrayBuffer:async()=>XLSX.write(book,{bookType:"xlsx",type:"array"})});
const result = await parseDelimitedFile(file(), { requiredFields: fields });
assert.equal(result.rows[0]["Item Number"], "000123");
assert.equal(result.rows[0]["Cost Total"], 1.23456);
XLSX.utils.book_append_sheet(book, sheet, "Otros costos");
await assert.rejects(parseDelimitedFile(file(), { requiredFields: fields }), /varias hojas/);
const parsed = await parseDelimitedFile({name:"scan.csv",arrayBuffer:async()=>new TextEncoder().encode('Número Parte QAD,Quantity,AreaName,extra\n00123,12,A1,visible').buffer});
assert.equal(rawScanObject(parsed.rows[0]).Quantity, "12");
assert.equal(rawScanObject(parsed.rows[0])["Número Parte QAD"], "00123");
assert.equal(rawScanObject(parsed.rows[0]).extra, "visible");
assert.equal(rawScanObject({numero_parte:"B",cantidad:8,area_escaneo:"A"}).Quantity,8);
assert.equal(rawScanObject({raw_record:{Quantity:6},cantidad:8}).Quantity,6);
const row = parent => ({"Parent Item":parent,Component:"C",Level:".2","Comp Phantom":"no",Usage:3});
const a = mergeBomLibrary(undefined,[row("A")],"a.txt","hash-a");
const b = mergeBomLibrary(undefined,[row("B")],"b.txt","hash-b");
const merged = combineLibraries(a,b);
assert.equal(merged.rows.length,2); assert.equal(merged.files.length,2);
assert.deepEqual(combineLibraries(merged,b),merged);
const conflict = mergeBomLibrary(undefined,[{...row("A"),Usage:9}],"conflict.txt","hash-c");
assert.throws(()=>combineLibraries(a,conflict),/cambia BOM/);
console.log("Imports OK: XLSX precision and IDs, ambiguous sheets, manual/bot viewer, shared BOM dedupe and conflicts");
