begin;
create table public.inventory_4wall_areas (id bigint generated always as identity primary key);
alter table public.inventory_4wall_areas add column if not exists "Id" text, add column if not exists "Nombre" text, add column if not exists "Descripcion" text, add column if not exists "Localidad QAD" text, add column if not exists "Responsable" text, add column if not exists "Área General" text, add column if not exists "Etiquetas" text, add column if not exists source_file text, add column if not exists source_sha256 text, add column if not exists source_row integer;
alter table public.inventory_4wall_areas enable row level security; revoke all on public.inventory_4wall_areas from anon, authenticated;
create unique index inventory_4wall_areas_source_row_unique on public.inventory_4wall_areas(source_sha256,source_row);

alter table public.escaneos_4wall add column if not exists "Ticket/FIFO" text, add column if not exists "AreaName" text, add column if not exists "subArea" text, add column if not exists "Escaneador" text, add column if not exists "auditor" text, add column if not exists "Numero de parte" text, add column if not exists "Número Parte QAD" text, add column if not exists "Quantity" text, add column if not exists "Costo Estándar" text, add column if not exists "Costo Total" text, add column if not exists "Responsable" text, add column if not exists "Área General" text, add column if not exists "Fecha agregado" text, add column if not exists "serial" text, add column if not exists source_file text, add column if not exists source_sha256 text, add column if not exists source_row integer;
create unique index escaneos_4wall_source_row_unique on public.escaneos_4wall(source_sha256,source_row);

create table public.inventory_qad_frozen (id bigint generated always as identity primary key);
alter table public.inventory_qad_frozen add column if not exists "Item Number" text, add column if not exists "Site" text, add column if not exists "Qty On Hand - Inv Mstr" text, add column if not exists "Quantity On Hand" text, add column if not exists "Location" text, add column if not exists "Lot/Serial" text, add column if not exists "Reference" text, add column if not exists "Inventory Status" text, add column if not exists "Status" text, add column if not exists "Item Type" text, add column if not exists "Expire Date" text, add column if not exists "Date Created" text, add column if not exists source_file text, add column if not exists source_sha256 text, add column if not exists source_row integer;
alter table public.inventory_qad_frozen enable row level security; revoke all on public.inventory_qad_frozen from anon, authenticated;
create unique index inventory_qad_frozen_source_row_unique on public.inventory_qad_frozen(source_sha256,source_row);

create table public.inventory_ispbb (id bigint generated always as identity primary key);
alter table public.inventory_ispbb add column if not exists "Site" text, add column if not exists "Location" text, add column if not exists "Item Number" text, add column if not exists "Description" text, add column if not exists "Status" text, add column if not exists "Item Type" text, add column if not exists "Master Schedule" text, add column if not exists "Plan Orders" text, add column if not exists "Order Policy" text, add column if not exists "Order Period" text, add column if not exists "Safety Stock" text, add column if not exists "Safety Time" text, add column if not exists "Buyer/Planner" text, add column if not exists "Issue Policy" text, add column if not exists "Phantom" text, add column if not exists "Order Multiple" text, add column if not exists "Network Code" text, add column if not exists "Purchase/Manufacture" text, add column if not exists source_file text, add column if not exists source_sha256 text, add column if not exists source_row integer;
alter table public.inventory_ispbb enable row level security; revoke all on public.inventory_ispbb from anon, authenticated;
create unique index inventory_ispbb_source_row_unique on public.inventory_ispbb(source_sha256,source_row);

create table public.inventory_bom_rows (id bigint generated always as identity primary key);
alter table public.inventory_bom_rows add column if not exists "Seq" text, add column if not exists "Parent Item" text, add column if not exists "Parent Item Description" text, add column if not exists "Parent UOM" text, add column if not exists "Parent Phantom" text, add column if not exists "Level" text, add column if not exists "Component" text, add column if not exists "Component Description" text, add column if not exists "Usage" text, add column if not exists "Grossed up Usage" text, add column if not exists "Comp UOM" text, add column if not exists "Op" text, add column if not exists "Comp Phantom" text, add column if not exists "Start Date" text, add column if not exists "End Date" text, add column if not exists "Product Line" text, add column if not exists "Item Type" text, add column if not exists "P/M" text, add column if not exists "Part Status" text, add column if not exists "Cost Total" text, add column if not exists "Ext Cost Total" text, add column if not exists "BOH" text, add column if not exists "Supplier" text, add column if not exists "Name" text, add column if not exists "Site" text, add column if not exists source_file text, add column if not exists source_sha256 text, add column if not exists source_row integer;
alter table public.inventory_bom_rows enable row level security; revoke all on public.inventory_bom_rows from anon, authenticated;
create unique index inventory_bom_rows_source_row_unique on public.inventory_bom_rows(source_sha256,source_row);

create table public.inventory_cost_parts (id bigint generated always as identity primary key);
alter table public.inventory_cost_parts add column if not exists "Site" text, add column if not exists "Item Number" text, add column if not exists "Description" text, add column if not exists "Description__2" text, add column if not exists "Unit of Measure" text, add column if not exists "Prod Line" text, add column if not exists "Item Type" text, add column if not exists "Status" text, add column if not exists "Group" text, add column if not exists "Purchase/Manufacture" text, add column if not exists "Cost Total" text, add column if not exists "Material" text, add column if not exists "Material LL" text, add column if not exists "Subcontract" text, add column if not exists "Subcontract LL" text, add column if not exists "Overhead" text, add column if not exists "Overhead LL" text, add column if not exists "Labor" text, add column if not exists "Labor LL" text, add column if not exists "Burden" text, add column if not exists "Burden LL" text, add column if not exists source_file text, add column if not exists source_sha256 text, add column if not exists source_row integer;
alter table public.inventory_cost_parts enable row level security; revoke all on public.inventory_cost_parts from anon, authenticated;
create unique index inventory_cost_parts_source_row_unique on public.inventory_cost_parts(source_sha256,source_row);
alter table public.escaneos_4wall add column if not exists raw_record jsonb, add column if not exists source_columns jsonb;
update public.escaneos_4wall set "Número Parte QAD"=numero_parte, "Quantity"=cantidad::text, "AreaName"=area_escaneo where "Número Parte QAD" is null;
create schema if not exists reconciler_archive; revoke all on schema reconciler_archive from public, anon, authenticated;
do $$ begin if exists(select 1 from public.dev_feedback) or exists(select 1 from public.reportes_investigacion) then raise exception 'Archive tables are no longer empty'; end if; end $$;
alter table public.dev_feedback set schema reconciler_archive; alter table public.reportes_investigacion set schema reconciler_archive;
revoke all on reconciler_archive.dev_feedback,reconciler_archive.reportes_investigacion from anon,authenticated;
commit;
select table_name,count(*) filter(where column_name not in ('id','source_file','source_sha256','source_row','numero_parte','cantidad','area_escaneo','fecha_hora','raw_record','source_columns')) source_columns from information_schema.columns where table_schema='public' and table_name in ('inventory_4wall_areas','escaneos_4wall','inventory_qad_frozen','inventory_ispbb','inventory_bom_rows','inventory_cost_parts') group by table_name order by table_name;